version: 0.0
os: linux
files:
  - source: ./install.txt
    destination: .
hooks:
  BeforeInstall:
    - location: ./scripts/before-install.sh
      timeout: 30
  AfterInstall:
    - location: ./scripts/after-install.sh
      timeout: 30
  ApplicationStart:
    - location: ./scripts/application-start.sh
      timeout: 30
  ValidateService:
    - location: ./scripts/validate-service.sh
      timeout: 30
