version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/1.sh
      timeout: 10
      runas: root
    - location: scripts/2.sh
      timeout: 10
      runas: root
  ApplicationStop:
    - location: scripts/3.sh
      timeout: 10
      runas: root

